#!/bin/bash
cat "/sys/cray/pm_counters/energy" >> genoa-pmc
cat "/sys/cray/pm_counters/cpu_energy" >> genoa-pmc
cat "/sys/cray/pm_counters/memory_energy" >> genoa-pmc &
wait

ulimit -s unlimited

numactl -m 0 -C 0 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 1 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 2 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 3 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 4 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 5 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 6 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 7 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 8 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 9 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 10 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 11 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 12 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 13 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 14 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 15 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 16 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 17 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 18 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 19 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 20 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 21 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 22 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 0 -C 23 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 24 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 25 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 26 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 27 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 28 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 29 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 30 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 31 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 32 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 33 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 34 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 35 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 36 perf record -e cpu-cycles,cpu-clock ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 37 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 38 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 39 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 40 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 41 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 42 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 43 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 44 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 45 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 46 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 1 -C 47 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 48 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 49 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 50 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 51 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 52 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 53 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 54 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 55 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 56 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 57 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 58 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 59 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 60 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 61 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 62 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 63 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 64 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 65 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 66 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 67 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 68 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 69 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 70 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 2 -C 71 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 72 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 73 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 74 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 75 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 76 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 77 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 78 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 79 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 80 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 81 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 82 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 83 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 84 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 85 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 86 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 87 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 88 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 89 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 90 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 91 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 92 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 93 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 94 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &
numactl -m 3 -C 95 ./xbwaves2017 < ./data/refrate/input/bwaves_1.in &

wait

cat "/sys/cray/pm_counters/energy" >> genoa-pmc
cat "/sys/cray/pm_counters/cpu_energy" >> genoa-pmc
cat "/sys/cray/pm_counters/memory_energy" >> genoa-pmc &
