#!/bin/bash
cat "/sys/cray/pm_counters/energy" >> genoa-pmc
cat "/sys/cray/pm_counters/cpu_energy" >> genoa-pmc
cat "/sys/cray/pm_counters/memory_energy" >> genoa-pmc &
wait

numactl -m 0 -C 0 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 1 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 2 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 3 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 4 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 5 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 6 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 7 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 8 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 9 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 10 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 11 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 12 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 13 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 14 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 15 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 16 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 17 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 18 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 19 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 20 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 21 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 22 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 0 -C 23 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 24 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 25 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 26 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 27 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 28 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 29 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 30 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 31 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 32 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 33 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 34 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 35 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 36 perf record -e cpu-cycles,cpu-clock ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 37 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 38 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 39 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 40 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 41 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 42 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 43 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 44 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 45 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 46 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 1 -C 47 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 48 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 49 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 50 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 51 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 52 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 53 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 54 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 55 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 56 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 57 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 58 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 59 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 60 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 61 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 62 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 63 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 64 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 65 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 66 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 67 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 68 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 69 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 70 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 2 -C 71 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 72 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 73 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 74 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 75 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 76 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 77 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 78 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 79 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 80 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 81 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 82 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 83 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 84 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 85 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 86 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 87 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 88 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 89 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 90 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 91 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 92 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 93 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 94 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &
numactl -m 3 -C 95 ./xroms2017 < data/refrate/input/ocean_benchmark2.in.x &

wait
cat "/sys/cray/pm_counters/energy" >> genoa-pmc
cat "/sys/cray/pm_counters/cpu_energy" >> genoa-pmc
cat "/sys/cray/pm_counters/memory_energy" >> genoa-pmc &
